<template>
  <section class="users-page">
    <header><div><p>USER ADMINISTRATION</p><h1>使用者管理</h1></div><button class="btn btn-primary" type="button" @click="startCreate"><i class="fas fa-user-plus"></i> 新增使用者</button></header>
    <div v-if="message" class="notice success">{{ message }}</div><div v-if="errorMessage" class="notice error">{{ errorMessage }}</div>
    <div class="table-card">
      <div class="tools"><div><strong>共 {{ users.length }} 位使用者</strong><span>登入密碼採不可逆雜湊，只能重設，無法顯示原密碼</span></div><input v-model.trim="search" type="search" placeholder="搜尋帳號、姓名或部門"></div>
      <div class="table-scroll"><table><thead><tr><th>ID</th><th>帳號</th><th>姓名</th><th>部門</th><th>狀態</th><th>權限</th><th>操作</th></tr></thead>
        <tbody><tr v-for="user in filteredUsers" :key="user.id"><td>{{ user.id }}</td><td>{{ user.username }}</td><td>{{ user.fullname || "—" }}</td><td>{{ user.department?.department_name || "—" }}</td><td><span :class="['status', user.is_active ? 'active' : 'inactive']">{{ user.is_active ? "啟用" : "停用" }}</span></td><td>{{ roleLabel(user) }}</td><td class="actions"><button class="edit" type="button" @click="startEdit(user)">編輯</button><button class="delete" type="button" :disabled="user.id === currentUserId" @click="remove(user)">刪除</button></td></tr><tr v-if="!loading && filteredUsers.length === 0"><td colspan="7" class="empty">沒有符合條件的使用者</td></tr></tbody>
      </table></div><div v-if="loading" class="loading">載入中…</div>
    </div>
    <div v-if="editorOpen" class="backdrop" @click.self="closeEditor"><form class="editor" @submit.prevent="save"><header><h2>{{ editingId ? "編輯使用者" : "新增使用者" }}</h2><button type="button" @click="closeEditor">×</button></header>
      <div class="fields"><label><span>帳號 *</span><input v-model.trim="form.username" required maxlength="100" autocomplete="off"></label><label><span>姓名 *</span><input v-model.trim="form.fullname" required maxlength="255"></label><label><span>部門 *</span><select v-model.number="form.department_id" required><option :value="0" disabled>請選擇部門</option><option v-for="department in departments" :key="department.id" :value="department.id">{{ department.department_name }}</option></select></label><label><span>{{ editingId ? "重設密碼（留空表示不變）" : "密碼 *" }}</span><div class="password-input"><input v-model="form.password" :required="!editingId" minlength="8" maxlength="72" :type="showTypedPassword ? 'text' : 'password'" autocomplete="new-password"><button type="button" :aria-label="showTypedPassword ? '隱藏輸入密碼' : '顯示輸入密碼'" @click="showTypedPassword = !showTypedPassword"><i :class="showTypedPassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i></button></div></label>
        <label class="check"><input v-model="form.is_active" type="checkbox"><span>帳號啟用</span></label><label class="check"><input v-model="form.is_superuser" type="checkbox"><span>系統管理員</span></label><label class="check"><input v-model="managerPermission" type="checkbox"><span>管理功能權限</span></label></div>
      <div v-if="editorError" class="notice error">{{ editorError }}</div><footer><button class="btn btn-outline-secondary" type="button" @click="closeEditor">取消</button><button class="btn btn-primary" :disabled="saving">{{ saving ? "儲存中…" : "儲存" }}</button></footer></form></div>
  </section>
</template>
<script>
import { createAdminUserAPI, deleteAdminUserAPI, getDepartmentsAPI, getUserAPI, updateAdminUserAPI } from "@/service/apis";
export default {
  name: "UserManagement",
  data: () => ({ users: [], departments: [], search: "", loading: false, editorOpen: false, editingId: null, saving: false, showTypedPassword: false, message: "", errorMessage: "", editorError: "", form: { username: "", fullname: "", password: "", department_id: 0, is_active: true, is_superuser: false, checklistAll_permission: 0 } }),
  computed: {
    currentUserId() { return Number(this.$store.getters.getUserId); },
    filteredUsers() { const term = this.search.toLowerCase(); if (!term) return this.users; return this.users.filter((user) => [user.username, user.fullname, user.department?.department_name].some((value) => String(value || "").toLowerCase().includes(term))); },
    managerPermission: { get() { return this.form.checklistAll_permission === 1; }, set(value) { this.form.checklistAll_permission = value ? 1 : 0; } },
  },
  mounted() { this.load(); },
  methods: {
    async load() { this.loading = true; this.errorMessage = ""; try { const [users, departments] = await Promise.all([getUserAPI(), getDepartmentsAPI()]); this.users = users.data; this.departments = departments.data; } catch (error) { this.errorMessage = error.response?.data?.detail || "無法載入使用者資料。"; } finally { this.loading = false; } },
    emptyForm() { return { username: "", fullname: "", password: "", department_id: 0, is_active: true, is_superuser: false, checklistAll_permission: 0 }; },
    startCreate() { this.editingId = null; this.form = this.emptyForm(); this.showTypedPassword = false; this.editorError = ""; this.editorOpen = true; },
    startEdit(user) { this.editingId = user.id; this.form = { username: user.username || "", fullname: user.fullname || "", password: "", department_id: user.department_id || 0, is_active: Boolean(user.is_active), is_superuser: Boolean(user.is_superuser), checklistAll_permission: user.checklistAll_permission || 0 }; this.showTypedPassword = false; this.editorError = ""; this.editorOpen = true; },
    closeEditor() { this.editorOpen = false; this.editorError = ""; },
    async save() { this.saving = true; this.editorError = ""; const payload = { ...this.form }; if (this.editingId && !payload.password) delete payload.password; try { if (this.editingId) await updateAdminUserAPI(this.editingId, payload); else await createAdminUserAPI(payload); this.closeEditor(); this.message = "使用者資料已儲存。"; await this.load(); } catch (error) { this.editorError = error.response?.data?.detail || "儲存失敗，請檢查輸入資料。"; } finally { this.saving = false; } },
    async remove(user) { if (user.id === this.currentUserId || !window.confirm(`確定刪除使用者 ${user.username}？`)) return; try { await deleteAdminUserAPI(user.id); this.message = "使用者已刪除。"; await this.load(); } catch (error) { this.errorMessage = error.response?.status === 409 ? "此使用者仍有報修或其他關聯資料，無法刪除；請改為停用帳號。" : (error.response?.data?.detail || "刪除失敗。"); } },
    roleLabel(user) { if (user.is_superuser) return "系統管理員"; if (user.checklistAll_permission === 1) return "管理者"; return "一般使用者"; },
  },
};
</script>
<style scoped>
.users-page{min-height:100%;padding:28px;background:#f3f6fa;color:#172033}.users-page>header{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px}.users-page header p{margin:0;color:#68809b;font-size:.72rem;font-weight:800;letter-spacing:.16em}.users-page h1{margin:4px 0 0}.notice{margin-bottom:14px;padding:12px 14px;border-radius:8px}.success{color:#067647;background:#ecfdf3}.error{color:#b42318;background:#fff0ef}.table-card{border:1px solid #dce4ee;border-radius:14px;background:#fff;box-shadow:0 10px 30px rgba(30,48,75,.06)}.tools{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:18px 20px}.tools div{display:flex;flex-direction:column}.tools span{color:#718096;font-size:.82rem}.tools input{width:min(360px,50%);padding:10px;border:1px solid #cbd5e1;border-radius:8px}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px 15px;border-top:1px solid #e8edf3;text-align:left;white-space:nowrap}th{color:#607089;background:#f8fafc}.actions{display:flex;gap:7px}.actions button{padding:6px 11px;border-radius:6px;background:#fff}.edit{color:#1769e0;border:1px solid #1769e0}.delete{color:#d92d20;border:1px solid #d92d20}.delete:disabled{opacity:.35}.status{padding:4px 8px;border-radius:999px;font-size:.8rem}.status.active{color:#067647;background:#dcfae6}.status.inactive{color:#b42318;background:#fee4e2}.empty,.loading{text-align:center;color:#718096}.loading{padding:20px}.backdrop{position:fixed;inset:0;z-index:1050;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.7)}.editor{width:min(680px,100%);max-height:calc(100vh - 40px);overflow:auto;border-radius:14px;background:#fff}.editor>header{display:flex;justify-content:space-between;padding:20px 24px;border-bottom:1px solid #e2e8f0}.editor h2{margin:0}.editor header button{border:0;background:transparent;font-size:1.8rem}.fields{display:grid;grid-template-columns:1fr 1fr;gap:16px;padding:24px}.fields label:not(.check){display:flex;flex-direction:column;gap:7px}.fields input:not([type=checkbox]),.fields select{padding:10px 12px;border:1px solid #cbd5e1;border-radius:8px}.check{display:flex;align-items:center;gap:8px}.editor .notice{margin:0 24px}.editor footer{display:flex;justify-content:flex-end;gap:10px;padding:20px 24px}@media(max-width:700px){.users-page{padding:16px}.users-page>header,.tools{align-items:stretch;flex-direction:column}.tools input{width:100%}.fields{grid-template-columns:1fr}}
.password-input{display:flex}.password-input input{flex:1;border-radius:8px 0 0 8px!important}.password-input button{width:44px;color:#1769e0;border:1px solid #cbd5e1;border-left:0;border-radius:0 8px 8px 0;background:#fff}
</style>
